Google drive
Dev-Ai-Lopers/DL-Utils pull request #2
Opened 2023-09-20 14:00 UTC by txuna

## 개요
사용자가 요청한 경로를 구글드라이브에 업로드하는 모듈 제작

## 관련 이슈 번호
#1 

## 리뷰 요청 전 체크
- [X] flake8, isort, black linting
- [X] 추가된 함수 및 클래스에 docstring 달기
- [X] 인수에 타입 힌트 넣기
- [X] 코드 동작 확인

2023-09-20 14:03 UTC, txuna commented
함수 호출 부분에서 업로드 함수를 호출했을 때 어떤 이유에서 안되었는지 자세히 알 수 있도록 raise보단 Error 값을 명시해서 적용했습니다.

2023-09-21 08:56 UTC, eddie94 requested changes

2023-09-21 08:56 UTC, eddie94 commented on dlutils/logging/README.md
> +# Google Drive Upload API
리드미는 소스 폴더에 작성하지 마시고 위키쪽에 작성해주세요
지금은 위키 안에 logging페이지를 만들어 놨으니 그쪽으로 옮겨주시기 바랍니다
또한 Prerequisites Dependency 는 리포지토리의 의존관계를 따라가므로 라이브러리를 추가로 설치하셨다면 
requirements.txt에 적어주세요

2023-09-21 08:56 UTC, eddie94 commented on dlutils/logging/gdrive.py
> +        파일이름의 확장자를 기반으로 해당 파일이 어떤 MEDIA TYPE을 지니는지 반환한다.
독스트링은 구글 형식으로 작성해주세요
```
  """Returns the size of a tensor.

  Args:
    input: A `Tensor` or `SparseTensor`.
    name: A name for the operation (optional).
    optimize: if true, encode the size as a constant when possible.
    out_type: (Optional) The specified non-quantized numeric output type of the
      operation. Defaults to `tf.int32`.

  Returns:
    A `Tensor` of type `out_type`. Defaults to `tf.int32`.
  """
```

2023-09-21 08:56 UTC, eddie94 commented on dlutils/logging/gdrive.py
> +        ex = name.split(".")[-1]
splitext 등으로 대체

2023-09-21 08:56 UTC, eddie94 commented on dlutils/logging/gdrive.py
> +MEDIA_TYPE = {
확장자는 보통 로그파일이나 모델파일을 올릴거라 될수있으면 확장자를 정해놓는건 나중에 문제가 생길것 같습니다
jpg 파일을 텍스트 형식으로 업로드 하고 구글 드라이브에서 다운받았을때 정상적으로 파일을 열 수 있는지
확인이 필요해 보입니다

이쪽은 별도로 이슈를 만들어 놓을테니 새롭게 브랜치를 파서 작업해주세요

2023-09-21 08:56 UTC, eddie94 commented on dlutils/logging/gdrive.py
> +    return f"DL-UTIL-RESULT-{now_str}"
f"RESULT-{now_str}"
로 설정해주세요

2023-09-21 08:56 UTC, eddie94 commented on dlutils/logging/gdrive.py
> +        인자로 주어진 top_folder에 요청한 파일일 미디어타입에 맞게 업로드를 진행한다.
파일일 -> 파일을
오타 수정

2023-09-21 08:56 UTC, eddie94 commented on dlutils/logging/README.md
> +import gdrive
이쪽에 나온 샘플코드는
래퍼 함수를 만들어서 라이브러리 처럼 쓸수있게 만들어주세요

2023-09-21 09:08 UTC, txuna commented on dlutils/logging/gdrive.py
> +MEDIA_TYPE = {
테스트결과 이미지 파일을 text/plain 미디어 타입으로 구글드라이브에 업로드하였을 때 드라이브 내에서는 텍스트파일로 인식하나 다운로드시 확장자가 남아있기 때문에 로컬에서는 이미지로 인식됩니다

그럼 모든 파일에 대해서 text/plain 형태로 올리면 될까요?

2023-09-21 09:31 UTC, eddie94 commented on dlutils/logging/gdrive.py
> +MEDIA_TYPE = {
그럼 모든 파일을 텍스트로 취급하는게 좋아보입니다
#3 이쪽에 해당 내용 적어주시면 이슈 클로즈 하겠습니다

2023-09-21 10:59 UTC, eddie94 commented on dlutils/logging/gdrive.py
> +MEDIA_TYPE = {
#3 이슈 해결

2023-10-02 05:19 UTC, txuna commented on dlutils/logging/gdrive.py
> +        파일이름의 확장자를 기반으로 해당 파일이 어떤 MEDIA TYPE을 지니는지 반환한다.
@eddie94 독스트링 작성시 주로 영어 작성 권장인가요?

2023-10-04 02:54 UTC, txuna commented on dlutils/logging/gdrive.py
> +        ex = name.split(".")[-1]
모든 파일을 text/plain으로 취급하기에 해당 메서드 삭제했습니다.

2023-10-04 02:55 UTC, txuna commented
1차 코드리뷰 반영하여 수정해서 다시 리퀘스트 날렸습니다.

2023-10-04 08:11 UTC, eddie94 requested changes

2023-10-04 08:11 UTC, eddie94 commented on dlutils/logging/gdrive.py
> +    return g.upload(path)
함수 호출시 프로그램을 종료시키는것이 좋습니다
try except로 Error.None이 반환되지 않는 경우 raise문으로 에러를 발생시켜주세요
에러문은 ERROR_STRING 그대로 쓰면 될거같고 적당히 ValueError 세우면 될것같아요

2023-10-04 08:11 UTC, eddie94 commented on requirements.txt
> +google-api-python-client==2.99.0
버전지정은 충돌이 일어나는 경우나 해당 버전에만 들어있는 함수나 클래스를 쓰는 경우에만 지정해주세요
딱히 충돌이 예상되지 않으면 버전지정 없이 라이브러리 이름만 적어주시면 됩니다

2023-10-04 10:04 UTC, eddie94 commented
LGTM

2023-10-04 10:05 UTC, eddie94 approved these changes

2023-10-04 10:05 UTC, merged